slogo_team09: mainApplication.Controller Class Reference
mainApplication.Controller Class Reference
Public Member Functions
Controller ()
void parseAndEvaluate (String s) throws Exception
int createWorkspace (GUI gui)
void setActive (int id)
void removeWS (int id)
Map< String, Double > getVariables ()
Map< String, CommandObject > getCommands ()
Map< Integer, Color > getColors ()
void clear ()
void saveMem (File f) throws Exception
void setLanguage (String language)
Private Attributes
List< Workspace > myWorkspaces
Parser myParser
int myActive
Workspace myActiveWS
Detailed Description
Definition at line 20 of file Controller.java.
Constructor & Destructor Documentation
mainApplication.Controller.Controller ()
Controller that coordinates between front end and back end keeps a list of workspaces and held by the GUI also contains the only parser
Definition at line 32 of file Controller.java.
Member Function Documentation
void mainApplication.Controller.clear ()
Definition at line 92 of file Controller.java.
References workspace.Workspace.clear().
int mainApplication.Controller.createWorkspace (GUI gui)
creates a new workspace, sets the gui it belongs to and add its as a observer and creates its furst turtle
Parameters
gui
Returns
Definition at line 56 of file Controller.java.
References workspace.Workspace.createTurtle().
Referenced by mainApplication.GUI.initiate().
Map<Integer, Color> mainApplication.Controller.getColors ()
Definition at line 88 of file Controller.java.
References workspace.Workspace.getColors().
Referenced by mainApplication.GUI.update(), and features.RunButtonFeature.updatePanes().
Map<String, CommandObject> mainApplication.Controller.getCommands ()
Definition at line 84 of file Controller.java.
References workspace.Workspace.getCommands().
Referenced by features.RunButtonFeature.updatePanes().
Map<String, Double> mainApplication.Controller.getVariables ()
Definition at line 80 of file Controller.java.
References workspace.Workspace.getVariables().
Referenced by components.VarsTab.setTabEditable(), and features.RunButtonFeature.updatePanes().
void mainApplication.Controller.parseAndEvaluate (String s) throws Exception
takes a string and parses it into a graph of nodes which is then evaluated on over the current workspace
Parameters
s
Exceptions
Exception
Definition at line 44 of file Controller.java.
References workspace.Workspace.evaluate(), and parser.Parser.parse().
Referenced by mainApplication.GUIShell.createOpenButton(), mainApplication.GUI.initiateKeyPress(), features.PenWidthSliderFeature.PenWidthSliderFeature(), features.RunButtonFeature.RunButtonFeature(), and components.VarsTab.setTabEditable().
void mainApplication.Controller.removeWS (int id)
Definition at line 76 of file Controller.java.
Referenced by mainApplication.GUIShell.createNewButton(), mainApplication.GUIShell.createOpenButton(), and mainApplication.GUIShell.GUIShell().
void mainApplication.Controller.saveMem (File f) throws Exception
saves Variables and Stored commands
Parameters
f
Exceptions
Exception
Definition at line 102 of file Controller.java.
References workspace.Workspace.writeMem().
Referenced by mainApplication.GUIShell.createSaveButton().
void mainApplication.Controller.setActive (int id)
sets active workspace
Parameters
id
Definition at line 71 of file Controller.java.
Referenced by mainApplication.GUIShell.createNewButton(), mainApplication.GUIShell.createOpenButton(), and mainApplication.GUIShell.GUIShell().
void mainApplication.Controller.setLanguage (String language)
Definition at line 112 of file Controller.java.
References parser.Parser.changeLanguage(), and properties.LanguageProperties.Language.
Referenced by features.LanguageComboFeature.LanguageComboFeature().
Member Data Documentation
int mainApplication.Controller.myActive private
Definition at line 24 of file Controller.java.
Workspace mainApplication.Controller.myActiveWS private
Definition at line 25 of file Controller.java.
Parser mainApplication.Controller.myParser private
Definition at line 23 of file Controller.java.
List<Workspace> mainApplication.Controller.myWorkspaces private
Definition at line 22 of file Controller.java.
The documentation for this class was generated from the following file:
/tmp/duke-compsci308-fall2014/slogo_team09/repository/src/mainApplication/Controller.java