slogo_team09: features.SettingsBar Class Reference
features.SettingsBar Class Reference
Public Member Functions
SettingsBar ()
void updateColorPicker (ColorPicker cp)
void addPenSlider (Slider slider)
void addComboBox (ComboBox cb)
void addAnimationSlider (Slider s)
void addButton (Button b)
Private Attributes
int mySceneHeight
RightPane myRightPane
LeftPane myLeftPane
ResourceBundle myNumberResources
Turtle myTurtle
ComboBox< String > languageCB
ComboBox< String > colourCB
ColorPicker displayColourPicker
Static Private Attributes
static int mySceneWidth
Detailed Description
Definition at line 28 of file SettingsBar.java.
Constructor & Destructor Documentation
features.SettingsBar.SettingsBar ()
Definition at line 40 of file SettingsBar.java.
Member Function Documentation
void features.SettingsBar.addAnimationSlider (Slider s)
adds slider to settings bar
Parameters
s slider to adjust animation speed
Definition at line 77 of file SettingsBar.java.
Referenced by mainApplication.GUI.loadPanes().
void features.SettingsBar.addButton (Button b)
adds button to settings bar
Parameters
b button
Definition at line 86 of file SettingsBar.java.
void features.SettingsBar.addComboBox (ComboBox cb)
adds combo box to settings bar
Parameters
cb combox box for pen style
Definition at line 67 of file SettingsBar.java.
Referenced by mainApplication.GUI.loadPanes().
void features.SettingsBar.addPenSlider (Slider slider)
adds slider to the settings bar
Parameters
slider slider to adjust pen size
Definition at line 55 of file SettingsBar.java.
Referenced by mainApplication.GUI.loadPanes().
void features.SettingsBar.updateColorPicker (ColorPicker cp)
adds color picker to the settings bar
Parameters
cp color picker for display color
Definition at line 48 of file SettingsBar.java.
Member Data Documentation
ComboBox<String> features.SettingsBar.colourCB private
Definition at line 37 of file SettingsBar.java.
ColorPicker features.SettingsBar.displayColourPicker private
Definition at line 38 of file SettingsBar.java.
ComboBox<String> features.SettingsBar.languageCB private
Definition at line 36 of file SettingsBar.java.
LeftPane features.SettingsBar.myLeftPane private
Definition at line 33 of file SettingsBar.java.
ResourceBundle features.SettingsBar.myNumberResources private
Definition at line 34 of file SettingsBar.java.
RightPane features.SettingsBar.myRightPane private
Definition at line 32 of file SettingsBar.java.
int features.SettingsBar.mySceneHeight private
Definition at line 30 of file SettingsBar.java.
int features.SettingsBar.mySceneWidth static private
Definition at line 31 of file SettingsBar.java.
Turtle features.SettingsBar.myTurtle private
Definition at line 35 of file SettingsBar.java.
The documentation for this class was generated from the following file:
/tmp/duke-compsci308-fall2014/slogo_team09/repository/src/features/SettingsBar.java