slogo_team09: command.Command Class Reference
command.Command Class Reference abstract
Public Member Functions
Command (String s)
int getNumInputs (Node node)
String toString ()
boolean isList ()
abstract double execute (List< Node > inputs, Workspace workspace) throws Exception
Protected Member Functions
Command (String s, int numInputs)
boolean checkListExit (Node node)
Protected Attributes
int myNumInputs
int myListFlag
String myString
Detailed Description
Definition at line 11 of file Command.java.
Constructor & Destructor Documentation
command.Command.Command (String s)
Creates a command with the given string as its name
Parameters
s name of command
Definition at line 23 of file Command.java.
command.Command.Command (String s, int numInputs) protected
Creates a command with the given string as its name and the given number of inputs
Parameters
s name of command
numInputs number of inputs for the command
Definition at line 37 of file Command.java.
Member Function Documentation
boolean command.Command.checkListExit (Node node) protected
Returns if the node is an end bracket
Parameters
node holding next command
Returns
if the node is an end bracket
Definition at line 74 of file Command.java.
References parser.Node.getCommand().
Referenced by command.Command.getNumInputs().
abstract double command.Command.execute (List< Node > inputs, Workspace workspace) throws Exception abstract
Executes the command in the workspace provided based on the inputs given and returns the appropriate double value
Parameters
inputs List of inputs for the specific command
workspace the command is being executed in
Returns
appropriate double based on the type of command
Exceptions
Exception if the command was unable to execute properly given the inputs it was given
Referenced by parser.Node.evaluate().
int command.Command.getNumInputs (Node node)
Returns the number of inputs for the specific command If it is a bracket command then it checks the next node to see if it is an end bracket
Parameters
node
Returns
number of inputs
Definition at line 49 of file Command.java.
References command.Command.checkListExit(), parser.Node.getCommand(), and command.Command.myNumInputs.
Referenced by parser.Parser.makeTree().
boolean command.Command.isList ()
Returns the current command is in a list
Returns
boolean if the current command is in a list
Definition at line 92 of file Command.java.
Referenced by parser.Parser.makeTree().
String command.Command.toString ()
Returns the commands name
Returns
command's name
Definition at line 83 of file Command.java.
References command.Command.myString.
Referenced by command.BaseMakeVariableCommand.checkCorrectInput(), command.BasicListCommand.checkListException(), command.VariableCommand.execute(), command.StoredCommand.execute(), parser.Parser.makeTree(), and parser.Node.toString().
Member Data Documentation
int command.Command.myListFlag protected
Definition at line 14 of file Command.java.
int command.Command.myNumInputs protected
Definition at line 13 of file Command.java.
Referenced by command.Command.getNumInputs().
String command.Command.myString protected
Definition at line 15 of file Command.java.
Referenced by command.StoredCommand.execute(), and command.Command.toString().
The documentation for this class was generated from the following file:
/tmp/duke-compsci308-fall2014/slogo_team09/repository/src/command/Command.java