slogo_team09: workspace.Workspace Class Reference
workspace.Workspace Class Reference
Public Member Functions
Workspace ()
Map< Integer, Color > getColors ()
void writeMem (File f) throws FileNotFoundException, UnsupportedEncodingException
void evaluate (List< Node > list) throws Exception
Map< String, Double > getVariables ()
Map< String, CommandObject > getCommands ()
void clear ()
void changeBackground (int i)
List< Turtle > getActiveTurtles ()
Map< Integer, Turtle > getTurtles ()
void update (Observable arg0, Object arg1)
void createTurtle (int id)
Private Member Functions
void initializeColors ()
void setChangedandNotify (Object arg1)
Private Attributes
Map< Integer, Turtle > myTurtles
StageProperties myStageProperties
Map< String, Double > myVariables
Map< String, CommandObject > myCommands
Map< Integer, Color > myColors
Static Private Attributes
static final String COLOR_PATH = "resources.constants/Color"
static final int DEFAULT_STAGE_COLOR = 0
static final boolean NOT_CLEAR = false
Detailed Description
Definition at line 22 of file Workspace.java.
Constructor & Destructor Documentation
workspace.Workspace.Workspace ()
Definition at line 32 of file Workspace.java.
References workspace.Workspace.initializeColors().
Member Function Documentation
void workspace.Workspace.changeBackground (int i)
Definition at line 91 of file Workspace.java.
References workspace.Workspace.setChangedandNotify(), and properties.StageProperties.setIndex().
void workspace.Workspace.clear ()
Definition at line 82 of file Workspace.java.
References workspace.Workspace.createTurtle(), workspace.Workspace.setChangedandNotify(), and properties.StageProperties.setClear().
Referenced by mainApplication.Controller.clear(), and command.ClearScreenCommand.execute().
void workspace.Workspace.createTurtle (int id)
Definition at line 121 of file Workspace.java.
References actor.Turtle.setChangedandNotify().
Referenced by workspace.Workspace.clear(), mainApplication.Controller.createWorkspace(), command.BaseMultiTurtleCommand.tell(), parser.TestParser.TestForward(), and parser.TestParser.TestTo().
void workspace.Workspace.evaluate (List< Node > list) throws Exception
Definition at line 67 of file Workspace.java.
Referenced by mainApplication.Controller.parseAndEvaluate().
List<Turtle> workspace.Workspace.getActiveTurtles ()
Definition at line 96 of file Workspace.java.
Referenced by parser.TestParser.TestForward().
Map<Integer, Color> workspace.Workspace.getColors ()
Definition at line 48 of file Workspace.java.
References workspace.Workspace.myColors.
Referenced by mainApplication.Controller.getColors().
Map<String, CommandObject> workspace.Workspace.getCommands ()
Definition at line 78 of file Workspace.java.
References workspace.Workspace.myCommands.
Referenced by mainApplication.Controller.getCommands().
Map<Integer, Turtle> workspace.Workspace.getTurtles ()
Definition at line 106 of file Workspace.java.
References workspace.Workspace.myTurtles.
Referenced by command.ClearScreenCommand.execute(), command.BaseMultiTurtleCommand.tell(), and parser.TestParser.TestTo().
Map<String, Double> workspace.Workspace.getVariables ()
Definition at line 74 of file Workspace.java.
References workspace.Workspace.myVariables.
Referenced by mainApplication.Controller.getVariables(), and command.BaseMakeVariableCommand.makeVariable().
void workspace.Workspace.initializeColors () private
Definition at line 41 of file Workspace.java.
Referenced by workspace.Workspace.Workspace().
void workspace.Workspace.setChangedandNotify (Object arg1) private
Definition at line 115 of file Workspace.java.
Referenced by workspace.Workspace.changeBackground(), workspace.Workspace.clear(), and workspace.Workspace.update().
void workspace.Workspace.update (Observable arg0, Object arg1)
Definition at line 111 of file Workspace.java.
References workspace.Workspace.setChangedandNotify().
void workspace.Workspace.writeMem (File f) throws FileNotFoundException, UnsupportedEncodingException
Definition at line 52 of file Workspace.java.
Referenced by mainApplication.Controller.saveMem(), and parser.TestModel.testWrite().
Member Data Documentation
final String workspace.Workspace.COLOR_PATH = "resources.constants/Color" static private
Definition at line 23 of file Workspace.java.
final int workspace.Workspace.DEFAULT_STAGE_COLOR = 0 static private
Definition at line 24 of file Workspace.java.
Map<Integer, Color> workspace.Workspace.myColors private
Definition at line 30 of file Workspace.java.
Referenced by workspace.Workspace.getColors().
Map<String, CommandObject> workspace.Workspace.myCommands private
Definition at line 29 of file Workspace.java.
Referenced by workspace.Workspace.getCommands().
StageProperties workspace.Workspace.myStageProperties private
Definition at line 27 of file Workspace.java.
Map<Integer, Turtle> workspace.Workspace.myTurtles private
Definition at line 26 of file Workspace.java.
Referenced by workspace.Workspace.getTurtles().
Map<String, Double> workspace.Workspace.myVariables private
Definition at line 28 of file Workspace.java.
Referenced by workspace.Workspace.getVariables().
final boolean workspace.Workspace.NOT_CLEAR = false static private
Definition at line 25 of file Workspace.java.
The documentation for this class was generated from the following file:
/tmp/duke-compsci308-fall2014/slogo_team09/repository/src/workspace/Workspace.java