slogo_team09: parser.TestParser Class Reference
parser.TestParser Class Reference
Public Member Functions
void TestSum () throws Exception
void TestDif () throws Exception
void TestProd () throws Exception
void TestQuotient () throws Exception
void TestRemainder () throws Exception
void TestMinus () throws Exception
void TestRandom () throws Exception
void TestTrig () throws Exception
void TestPow () throws Exception
void TestBoolean () throws Exception
void TestIf () throws Exception
void TestIfElse () throws Exception
void TestSum2 () throws Exception
void TestForward () throws Exception
void TestMake () throws Exception
void TestRepeat () throws Exception
void TestFor () throws Exception
void TestTo () throws Exception
void TestRecursion () throws Exception
Detailed Description
Definition at line 8 of file TestParser.java.
Member Function Documentation
void parser.TestParser.TestBoolean () throws Exception
Definition at line 83 of file TestParser.java.
References parser.Parser.parse().
void parser.TestParser.TestDif () throws Exception
Definition at line 18 of file TestParser.java.
References parser.Parser.parse().
void parser.TestParser.TestFor () throws Exception
Definition at line 159 of file TestParser.java.
References parser.Parser.parse().
void parser.TestParser.TestForward () throws Exception
Definition at line 132 of file TestParser.java.
References workspace.Workspace.createTurtle(), workspace.Workspace.getActiveTurtles(), and parser.Parser.parse().
void parser.TestParser.TestIf () throws Exception
Definition at line 95 of file TestParser.java.
References parser.Parser.parse().
void parser.TestParser.TestIfElse () throws Exception
Definition at line 106 of file TestParser.java.
References parser.Parser.parse().
void parser.TestParser.TestMake () throws Exception
Definition at line 142 of file TestParser.java.
References parser.Parser.parse().
void parser.TestParser.TestMinus () throws Exception
Definition at line 49 of file TestParser.java.
References parser.Parser.parse().
void parser.TestParser.TestPow () throws Exception
Definition at line 75 of file TestParser.java.
References parser.Parser.parse().
void parser.TestParser.TestProd () throws Exception
Definition at line 25 of file TestParser.java.
References parser.Parser.parse().
void parser.TestParser.TestQuotient () throws Exception
Definition at line 32 of file TestParser.java.
References parser.Parser.parse().
void parser.TestParser.TestRandom () throws Exception
Definition at line 57 of file TestParser.java.
References parser.Parser.parse().
void parser.TestParser.TestRecursion () throws Exception
Definition at line 181 of file TestParser.java.
References parser.Parser.parse().
void parser.TestParser.TestRemainder () throws Exception
Definition at line 39 of file TestParser.java.
References parser.Parser.parse().
void parser.TestParser.TestRepeat () throws Exception
Definition at line 150 of file TestParser.java.
References parser.Parser.parse().
void parser.TestParser.TestSum () throws Exception
Definition at line 10 of file TestParser.java.
References parser.Parser.parse().
void parser.TestParser.TestSum2 () throws Exception
Definition at line 122 of file TestParser.java.
References parser.Parser.parse().
void parser.TestParser.TestTo () throws Exception
Definition at line 165 of file TestParser.java.
References workspace.Workspace.createTurtle(), workspace.Workspace.getTurtles(), actor.Turtle.getX(), and parser.Parser.parse().
void parser.TestParser.TestTrig () throws Exception
Definition at line 65 of file TestParser.java.
References parser.Parser.parse().
The documentation for this class was generated from the following file:
/tmp/duke-compsci308-fall2014/slogo_team09/repository/src/parser/TestParser.java