slogo_team09: properties.TurtleProperties Class Reference
properties.TurtleProperties Class Reference
Public Member Functions
TurtleProperties (Turtle turtle)
int getID ()
Pen getPen ()
Position getPosition ()
boolean isShowing ()
int getShape ()
Private Attributes
int myID
Pen myPen
Position myPosition
boolean myShowing
int myShape
Detailed Description
Passive Data Object for Turtle
Author
Chase Malik, Timesh Patel
Definition at line 13 of file TurtleProperties.java.
Constructor & Destructor Documentation
properties.TurtleProperties.TurtleProperties (Turtle turtle)
Definition at line 20 of file TurtleProperties.java.
References actor.Turtle.getID(), actor.Turtle.getPen(), actor.Turtle.getPosition(), actor.Turtle.getShape(), and actor.Turtle.isShowing().
Member Function Documentation
int properties.TurtleProperties.getID ()
Definition at line 28 of file TurtleProperties.java.
References properties.TurtleProperties.myID.
Pen properties.TurtleProperties.getPen ()
Definition at line 32 of file TurtleProperties.java.
References properties.TurtleProperties.myPen.
Position properties.TurtleProperties.getPosition ()
Definition at line 36 of file TurtleProperties.java.
References properties.TurtleProperties.myPosition.
int properties.TurtleProperties.getShape ()
Definition at line 44 of file TurtleProperties.java.
References properties.TurtleProperties.myShape.
boolean properties.TurtleProperties.isShowing ()
Definition at line 40 of file TurtleProperties.java.
References properties.TurtleProperties.myShowing.
Member Data Documentation
int properties.TurtleProperties.myID private
Definition at line 14 of file TurtleProperties.java.
Referenced by properties.TurtleProperties.getID().
Pen properties.TurtleProperties.myPen private
Definition at line 15 of file TurtleProperties.java.
Referenced by properties.TurtleProperties.getPen().
Position properties.TurtleProperties.myPosition private
Definition at line 16 of file TurtleProperties.java.
Referenced by properties.TurtleProperties.getPosition().
int properties.TurtleProperties.myShape private
Definition at line 18 of file TurtleProperties.java.
Referenced by properties.TurtleProperties.getShape().
boolean properties.TurtleProperties.myShowing private
Definition at line 17 of file TurtleProperties.java.
Referenced by properties.TurtleProperties.isShowing().
The documentation for this class was generated from the following file:
/tmp/duke-compsci308-fall2014/slogo_team09/repository/src/properties/TurtleProperties.java