slogo_team09: properties.PenProperties Class Reference
properties.PenProperties Class Reference
Public Member Functions
PenProperties (Pen pen)
boolean isDown ()
double size ()
Integer getColorIndex ()
int getID ()
Private Attributes
Pen myPen
Detailed Description
Passive Data Object for Pen
Author
Chase Malik, Timesh Patel
Definition at line 12 of file PenProperties.java.
Constructor & Destructor Documentation
properties.PenProperties.PenProperties (Pen pen)
Definition at line 15 of file PenProperties.java.
Member Function Documentation
Integer properties.PenProperties.getColorIndex ()
Definition at line 27 of file PenProperties.java.
References actor.Pen.getColorIndex().
Referenced by components.TurtleManager.updatePenProperties().
int properties.PenProperties.getID ()
Definition at line 31 of file PenProperties.java.
References actor.Pen.getID().
Referenced by components.TurtleManager.updatePenProperties().
boolean properties.PenProperties.isDown ()
Definition at line 19 of file PenProperties.java.
References actor.Pen.isDown().
Referenced by components.TurtleManager.updatePenProperties().
double properties.PenProperties.size ()
Definition at line 23 of file PenProperties.java.
References actor.Pen.getSize().
Referenced by components.TurtleManager.updatePenProperties().
Member Data Documentation
Pen properties.PenProperties.myPen private
Definition at line 13 of file PenProperties.java.
The documentation for this class was generated from the following file:
/tmp/duke-compsci308-fall2014/slogo_team09/repository/src/properties/PenProperties.java