slogo_team09: command.BaseMultiTurtleCommand Class Reference
command.BaseMultiTurtleCommand Class Reference abstract
Public Member Functions
BaseMultiTurtleCommand (String s, int numInputs, int numLists)
Public Member Functions inherited from command.BasicListCommand
BasicListCommand (String s, int numInputs, int numLists)
boolean checkListExit (Node node)
void checkListException (List< Node > inputs) throws Exception
int getBracketIndex (List< Node > inputs)
Public Member Functions inherited from command.Command
Command (String s)
int getNumInputs (Node node)
String toString ()
boolean isList ()
abstract double execute (List< Node > inputs, Workspace workspace) throws Exception
Protected Member Functions
List< Integer > getIds (List< Turtle > turtles)
List< Integer > getIdsList (List< Node > inputs, Workspace workspace) throws Exception
void tell (List< Integer > ids, Workspace workspace)
Protected Member Functions inherited from command.Command
Command (String s, int numInputs)
boolean checkListExit (Node node)
Additional Inherited Members
Protected Attributes inherited from command.Command
int myNumInputs
int myListFlag
String myString
Detailed Description
Definition at line 15 of file BaseMultiTurtleCommand.java.
Constructor & Destructor Documentation
command.BaseMultiTurtleCommand.BaseMultiTurtleCommand (String s, int numInputs, int numLists)
command sub hierarchy for commands that involve multiple turtles and setting particular ones active
Parameters
s
numInputs
numLists
Definition at line 23 of file BaseMultiTurtleCommand.java.
Member Function Documentation
List<Integer> command.BaseMultiTurtleCommand.getIds (List< Turtle > turtles) protected
returns list of Integers corresponding to ids from a list of turtles
Parameters
turtles
Returns
Definition at line 31 of file BaseMultiTurtleCommand.java.
Referenced by command.AskCommand.execute(), and command.AskWithCommand.execute().
List<Integer> command.BaseMultiTurtleCommand.getIdsList (List< Node > inputs, Workspace workspace) throws Exception protected
returns a list of Integers from a list of inputs from the beginning until the first end bracket
Parameters
inputs
workspace
Returns
Exceptions
Exception
Definition at line 46 of file BaseMultiTurtleCommand.java.
References command.BasicListCommand.getBracketIndex().
Referenced by command.AskCommand.execute(), and command.TellCommand.execute().
void command.BaseMultiTurtleCommand.tell (List< Integer > ids, Workspace workspace) protected
takes a list of integers corresponding to ids and tells the workspace to set those turtles to active or to create them
Parameters
ids
workspace
Definition at line 60 of file BaseMultiTurtleCommand.java.
References workspace.Workspace.createTurtle(), and workspace.Workspace.getTurtles().
Referenced by command.AskCommand.execute(), command.TellCommand.execute(), and command.AskWithCommand.execute().
The documentation for this class was generated from the following file:
/tmp/duke-compsci308-fall2014/slogo_team09/repository/src/command/BaseMultiTurtleCommand.java