slogo_team09: components.CenterPane Class Reference
components.CenterPane Class Reference
Public Member Functions
CenterPane ()
void update ()
void updateTurtlePosition (TurtleProperties pos)
void updatePenProperties (PenProperties props)
void clearScreen (boolean clear)
void updatePenType (int type)
void updateAnimate (boolean bool)
void initiateColorsMap (Map< Integer, Color > map)
void updateAnimationSpeed (double speed)
void updateBackgroundColor (int index)
Public Attributes
TurtleManager myTurtleManager
GridPane referenceGrid
Map< Integer, Color > colorsMap
boolean animate
Private Member Functions
GridPane createReferenceGrid ()
Detailed Description
Definition at line 16 of file CenterPane.java.
Constructor & Destructor Documentation
components.CenterPane.CenterPane ()
Definition at line 23 of file CenterPane.java.
References components.CenterPane.createReferenceGrid(), and components.TurtleManager.myTurtleMap.
Member Function Documentation
void components.CenterPane.clearScreen (boolean clear)
clears the screen and resets to one turtle
Parameters
clear states whether or not screen is to be cleared
Definition at line 66 of file CenterPane.java.
References components.TurtleManager.clearScreen().
Referenced by mainApplication.GUI.update().
GridPane components.CenterPane.createReferenceGrid () private
creates and adds reference grid to center pane
Returns
: gridpane that acts as reference grid
Definition at line 96 of file CenterPane.java.
Referenced by components.CenterPane.CenterPane().
void components.CenterPane.initiateColorsMap (Map< Integer, Color > map)
Definition at line 113 of file CenterPane.java.
Referenced by mainApplication.GUI.update().
void components.CenterPane.update ()
Implements features.Feature.
Definition at line 37 of file CenterPane.java.
void components.CenterPane.updateAnimate (boolean bool)
updates the animation on/off on all turtles in workspace
Parameters
bool states whether or not animation should be turned on
Definition at line 84 of file CenterPane.java.
References components.TurtleManager.myTurtleMap.
Referenced by features.AnimateButtonFeature.AnimateButtonFeature().
void components.CenterPane.updateAnimationSpeed (double speed)
Definition at line 117 of file CenterPane.java.
References components.TurtleManager.myTurtleMap.
Referenced by features.AnimationSpeedSliderFeature.AnimationSpeedSliderFeature().
void components.CenterPane.updateBackgroundColor (int index)
Definition at line 124 of file CenterPane.java.
Referenced by mainApplication.GUI.update().
void components.CenterPane.updatePenProperties (PenProperties props)
updates pen information
Parameters
props contains pen property information
Definition at line 59 of file CenterPane.java.
References components.TurtleManager.updatePenProperties().
Referenced by mainApplication.GUI.update().
void components.CenterPane.updatePenType (int type)
updates the pen style on all turtles in workspace
Parameters
type integer that corresponds to a specific line style
Definition at line 74 of file CenterPane.java.
References components.TurtleManager.myTurtleMap.
Referenced by features.PenTypeComboBoxFeature.PenTypeComboBoxFeature().
void components.CenterPane.updateTurtlePosition (TurtleProperties pos)
updates the turtle position using specified turlte ID
Parameters
pos contains information on coordinates and angle
Definition at line 45 of file CenterPane.java.
References components.TurtleManager.myTurtleMap, and components.TurtleManager.update().
Referenced by mainApplication.GUI.update().
Member Data Documentation
boolean components.CenterPane.animate
Definition at line 21 of file CenterPane.java.
Referenced by features.AnimateButtonFeature.AnimateButtonFeature().
Map<Integer, Color> components.CenterPane.colorsMap
Definition at line 20 of file CenterPane.java.
Referenced by components.TurtleManager.updatePenProperties().
TurtleManager components.CenterPane.myTurtleManager
Definition at line 18 of file CenterPane.java.
Referenced by mainApplication.GUI.loadPanes(), and features.RunButtonFeature.updatePanes().
GridPane components.CenterPane.referenceGrid
Definition at line 19 of file CenterPane.java.
Referenced by components.TurtleManager.clearScreen(), and features.ToggleGridButtonFeature.ToggleGridButtonFeature().
The documentation for this class was generated from the following file:
/tmp/duke-compsci308-fall2014/slogo_team09/repository/src/components/CenterPane.java