slogo_team09: parser.Node Class Reference
parser.Node Class Reference
Public Member Functions
Node (Command com)
double evaluate (Workspace workspace) throws Exception
void addChild (Node node)
Command getCommand ()
List< Node > getChildren ()
String toString ()
Private Attributes
List< Node > myChildren
Command myCommand
Detailed Description
Definition at line 9 of file Node.java.
Constructor & Destructor Documentation
parser.Node.Node (Command com)
Node class takes a command to put in a tree for parsing
Parameters
com This nodes Command
Definition at line 19 of file Node.java.
Member Function Documentation
void parser.Node.addChild (Node node)
adds a child node which will be another command or int that this command needs to execute ie a forward command would need a child with an int parameter
Definition at line 40 of file Node.java.
Referenced by parser.Parser.makeTree(), parser.TestModel.testLessCommand(), and parser.TestModel.testSumCommand().
double parser.Node.evaluate (Workspace workspace) throws Exception
returns the value of the this command and executes this command as well as all its children
Returns
Exceptions
Exception
Definition at line 31 of file Node.java.
References command.Command.execute().
Referenced by parser.TestModel.testLessCommand(), and parser.TestModel.testSumCommand().
List<Node> parser.Node.getChildren ()
Definition at line 53 of file Node.java.
References parser.Node.myChildren.
Command parser.Node.getCommand ()
returns this nodes command
Returns
Definition at line 49 of file Node.java.
References parser.Node.myCommand.
Referenced by command.BasicListCommand.checkListExit(), command.Command.checkListExit(), command.Command.getNumInputs(), parser.Parser.makeTree(), and parser.Node.toString().
String parser.Node.toString ()
Definition at line 57 of file Node.java.
References parser.Node.getCommand(), and command.Command.toString().
Member Data Documentation
List<Node> parser.Node.myChildren private
Definition at line 11 of file Node.java.
Referenced by parser.Node.getChildren().
Command parser.Node.myCommand private
Definition at line 12 of file Node.java.
Referenced by parser.Node.getCommand().
The documentation for this class was generated from the following file:
/tmp/duke-compsci308-fall2014/slogo_team09/repository/src/parser/Node.java