slogo_team09: components.TurtleManager Class Reference
components.TurtleManager Class Reference
Public Member Functions
TurtleManager (CenterPane pane)
void updateImageMap (Map< Integer, ImageView > imageMap)
void update (TurtleProperties props) throws NullPointerException
void updatePenProperties (PenProperties props)
void clearScreen (boolean clear)
Public Attributes
Map< Integer, DisplayTurtle > myTurtleMap
Private Attributes
CenterPane myCenterPane
BottomPane myBottomPane
Color testC
Map< Integer, ImageView > myImageMap
Detailed Description
TurtleManager is a class that maintains a list of graphic turtles that are displayed to the user. It updates the pen and turtle positions.
Definition at line 17 of file TurtleManager.java.
Constructor & Destructor Documentation
components.TurtleManager.TurtleManager (CenterPane pane)
Definition at line 24 of file TurtleManager.java.
Member Function Documentation
void components.TurtleManager.clearScreen (boolean clear)
Definition at line 61 of file TurtleManager.java.
References components.CenterPane.referenceGrid.
Referenced by components.CenterPane.clearScreen().
void components.TurtleManager.update (TurtleProperties props) throws NullPointerException
Definition at line 33 of file TurtleManager.java.
References features.DisplayTurtle.updateImageView(), features.DisplayTurtle.updatePosition(), and features.DisplayTurtle.updateTurtleShow().
Referenced by components.CenterPane.updateTurtlePosition().
void components.TurtleManager.updateImageMap (Map< Integer, ImageView > imageMap)
Definition at line 30 of file TurtleManager.java.
Referenced by mainApplication.GUI.loadPanes(), and features.RunButtonFeature.updatePanes().
void components.TurtleManager.updatePenProperties (PenProperties props)
Definition at line 50 of file TurtleManager.java.
References components.CenterPane.colorsMap, properties.PenProperties.getColorIndex(), properties.PenProperties.getID(), properties.PenProperties.isDown(), features.DisplayTurtle.myPen, properties.PenProperties.size(), features.Pen.updatePenColor(), features.DisplayTurtle.updatePenShow(), and features.Pen.updatePenWidth().
Referenced by components.CenterPane.updatePenProperties().
Member Data Documentation
BottomPane components.TurtleManager.myBottomPane private
Definition at line 20 of file TurtleManager.java.
CenterPane components.TurtleManager.myCenterPane private
Definition at line 19 of file TurtleManager.java.
Map<Integer, ImageView> components.TurtleManager.myImageMap private
Definition at line 22 of file TurtleManager.java.
Map<Integer, DisplayTurtle> components.TurtleManager.myTurtleMap
Definition at line 18 of file TurtleManager.java.
Referenced by components.CenterPane.CenterPane(), components.CenterPane.updateAnimate(), components.CenterPane.updateAnimationSpeed(), components.CenterPane.updatePenType(), and components.CenterPane.updateTurtlePosition().
Color components.TurtleManager.testC private
Definition at line 21 of file TurtleManager.java.
The documentation for this class was generated from the following file:
/tmp/duke-compsci308-fall2014/slogo_team09/repository/src/components/TurtleManager.java