slogo_team09: components.VarsTab Class Reference
components.VarsTab Class Reference
Public Member Functions
VarsTab (String s, Controller c)
void update (Object o)
Public Member Functions inherited from components.InfoTab
InfoTab (String s, Controller c)
void clear ()
void update ()
void update (Object o)
Package Attributes
Map< String, Double > myVars
Private Member Functions
void setTabEditable (Button edit)
Additional Inherited Members
Protected Attributes inherited from components.InfoTab
GridPane myTextPane
VBox myDrawer
int myTextIndex
Controller myController
Detailed Description
VarsTab is a subclass of InfoTab that holds the variables in the workspace. These can be edited with the "edit" button, and saved to workspace
Definition at line 24 of file VarsTab.java.
Constructor & Destructor Documentation
components.VarsTab.VarsTab (String s, Controller c)
Definition at line 26 of file VarsTab.java.
References components.InfoTab.myDrawer, and components.VarsTab.setTabEditable().
Member Function Documentation
void components.VarsTab.setTabEditable (Button edit) private
Definition at line 52 of file VarsTab.java.
References mainApplication.Controller.getVariables(), components.InfoTab.myController, components.InfoTab.myDrawer, components.InfoTab.myTextIndex, components.InfoTab.myTextPane, mainApplication.Controller.parseAndEvaluate(), and components.VarsTab.update().
Referenced by components.VarsTab.VarsTab().
void components.VarsTab.update (Object o)
Definition at line 40 of file VarsTab.java.
References components.InfoTab.myTextIndex, and components.InfoTab.myTextPane.
Referenced by components.VarsTab.setTabEditable().
Member Data Documentation
Map<String, Double> components.VarsTab.myVars package
Definition at line 25 of file VarsTab.java.
The documentation for this class was generated from the following file:
/tmp/duke-compsci308-fall2014/slogo_team09/repository/src/components/VarsTab.java