slogo_team09: features.Pen Class Reference
features.Pen Class Reference
Public Member Functions
Pen ()
Line drawLine (double x, double y, double tWidth, double tHeight, int type)
void updatePenColor (Color color)
void updatePenWidth (double width)
Public Attributes
double middleX
double middleY
Private Attributes
double penX
double penY
double penWidth
double turtleWidth
double turtleHeight
Color penColor
Detailed Description
Definition at line 10 of file Pen.java.
Constructor & Destructor Documentation
features.Pen.Pen ()
Definition at line 23 of file Pen.java.
References features.Pen.middleX, and features.Pen.middleY.
Member Function Documentation
Line features.Pen.drawLine (double x, double y, double tWidth, double tHeight, int type)
Parameters
x new x coordinate
y new y coordinate
tWidth turtle width to take offset into consideration
tHeight turtle height to take offset into consideration
type integer that corresponds to the correct line style to be drawn
Returns
a line that is to be added to center pane
Definition at line 43 of file Pen.java.
Referenced by features.DisplayTurtle.updateLine().
void features.Pen.updatePenColor (Color color)
Updates the pen color
Parameters
color color that the pen is updated to
Definition at line 78 of file Pen.java.
Referenced by components.TurtleManager.updatePenProperties().
void features.Pen.updatePenWidth (double width)
updates the size of pen (size of lines drawn)
Parameters
width size of pen(line) to be updated to
Definition at line 86 of file Pen.java.
Referenced by components.TurtleManager.updatePenProperties().
Member Data Documentation
double features.Pen.middleX
Definition at line 17 of file Pen.java.
Referenced by features.Pen.Pen().
double features.Pen.middleY
Definition at line 18 of file Pen.java.
Referenced by features.Pen.Pen().
Color features.Pen.penColor private
Definition at line 19 of file Pen.java.
double features.Pen.penWidth private
Definition at line 14 of file Pen.java.
double features.Pen.penX private
Definition at line 12 of file Pen.java.
double features.Pen.penY private
Definition at line 13 of file Pen.java.
double features.Pen.turtleHeight private
Definition at line 16 of file Pen.java.
double features.Pen.turtleWidth private
Definition at line 15 of file Pen.java.
The documentation for this class was generated from the following file:
/tmp/duke-compsci308-fall2014/slogo_team09/repository/src/features/Pen.java