slogo_team09: mainApplication.GUIShell Class Reference
mainApplication.GUIShell Class Reference
Public Member Functions
GUIShell (Controller controller, Stage stage)
Private Member Functions
Button createNewButton ()
Button createSaveButton ()
Button createOpenButton ()
Private Attributes
ToolBar myToolBar
TabPane myTabPane
Controller myController
Stage myStage
Detailed Description
Definition at line 23 of file GUIShell.java.
Constructor & Destructor Documentation
mainApplication.GUIShell.GUIShell (Controller controller, Stage stage)
Definition at line 28 of file GUIShell.java.
References mainApplication.GUIShell.createNewButton(), mainApplication.GUIShell.createOpenButton(), mainApplication.GUIShell.createSaveButton(), mainApplication.GUI.initiate(), mainApplication.Controller.removeWS(), and mainApplication.Controller.setActive().
Member Function Documentation
Button mainApplication.GUIShell.createNewButton () private
Definition at line 70 of file GUIShell.java.
References mainApplication.GUI.initiate(), mainApplication.GUI.myGUIid, mainApplication.Controller.removeWS(), and mainApplication.Controller.setActive().
Referenced by mainApplication.GUIShell.GUIShell().
Button mainApplication.GUIShell.createOpenButton () private
Definition at line 134 of file GUIShell.java.
References mainApplication.GUI.initiate(), mainApplication.GUI.myBottomPane, mainApplication.Controller.parseAndEvaluate(), mainApplication.Controller.removeWS(), mainApplication.Controller.setActive(), and components.BottomPane.updateErrors().
Referenced by mainApplication.GUIShell.GUIShell().
Button mainApplication.GUIShell.createSaveButton () private
Definition at line 111 of file GUIShell.java.
References mainApplication.Controller.saveMem().
Referenced by mainApplication.GUIShell.GUIShell().
Member Data Documentation
Controller mainApplication.GUIShell.myController private
Definition at line 26 of file GUIShell.java.
Stage mainApplication.GUIShell.myStage private
Definition at line 27 of file GUIShell.java.
TabPane mainApplication.GUIShell.myTabPane private
Definition at line 25 of file GUIShell.java.
ToolBar mainApplication.GUIShell.myToolBar private
Definition at line 24 of file GUIShell.java.
The documentation for this class was generated from the following file:
/tmp/duke-compsci308-fall2014/slogo_team09/repository/src/mainApplication/GUIShell.java