slogo_team09: command.StoredCommand Class Reference
command.StoredCommand Class Reference
Public Member Functions
StoredCommand (String s)
double execute (List< Node > inputs, Workspace workspace) throws Exception
Public Member Functions inherited from command.BaseMakeVariableCommand
BaseMakeVariableCommand (String s, int numInputs, int numLists)
void makeVariable (String name, double value, Workspace workspace)
Public Member Functions inherited from command.BasicListCommand
BasicListCommand (String s, int numInputs, int numLists)
boolean checkListExit (Node node)
void checkListException (List< Node > inputs) throws Exception
int getBracketIndex (List< Node > inputs)
Public Member Functions inherited from command.Command
Command (String s)
int getNumInputs (Node node)
String toString ()
boolean isList ()
abstract double execute (List< Node > inputs, Workspace workspace) throws Exception
Additional Inherited Members
Protected Member Functions inherited from command.BaseMakeVariableCommand
void checkCorrectInput (List< Node > inputs, int i)
Protected Member Functions inherited from command.Command
Command (String s, int numInputs)
boolean checkListExit (Node node)
Protected Attributes inherited from command.Command
int myNumInputs
int myListFlag
String myString
Detailed Description
Definition at line 11 of file StoredCommand.java.
Constructor & Destructor Documentation
command.StoredCommand.StoredCommand (String s)
Definition at line 13 of file StoredCommand.java.
Member Function Documentation
double command.StoredCommand.execute (List< Node > inputs, Workspace workspace) throws Exception
Definition at line 18 of file StoredCommand.java.
References command.BasicListCommand.checkListException(), parser.CommandObject.getMyCommands(), parser.CommandObject.getMyNumVars(), parser.CommandObject.getMyVarNames(), command.BaseMakeVariableCommand.makeVariable(), command.Command.myString, and command.Command.toString().
The documentation for this class was generated from the following file:
/tmp/duke-compsci308-fall2014/slogo_team09/repository/src/command/StoredCommand.java