slogo_team09: actor.Pen Class Reference
actor.Pen Class Reference
Public Member Functions
Pen (int id)
int getID ()
double getSize ()
void setSize (double size)
boolean isDown ()
void setDown (boolean b)
int getColorIndex ()
void setColorIndex (int i)
Private Attributes
boolean myDown
double mySize
int myColorIndex
int myID
Static Private Attributes
static final double DEFAULT_SIZE = 1
static final int DEFAULT_COLOR_INDEX = 1
Detailed Description
Author
Timesh Patel, Chase Malik
Definition at line 6 of file Pen.java.
Constructor & Destructor Documentation
actor.Pen.Pen (int id)
Pen class represents the pen of a turtle has size, width, a color index, id of the turtle it belongs to and whether its up or down
Parameters
id
Definition at line 22 of file Pen.java.
References actor.Pen.DEFAULT_COLOR_INDEX, and actor.Pen.DEFAULT_SIZE.
Member Function Documentation
int actor.Pen.getColorIndex ()
Definition at line 49 of file Pen.java.
References actor.Pen.myColorIndex.
Referenced by command.GetPenColorCommand.execute(), and properties.PenProperties.getColorIndex().
int actor.Pen.getID ()
Definition at line 29 of file Pen.java.
References actor.Pen.myID.
Referenced by properties.PenProperties.getID().
double actor.Pen.getSize ()
Definition at line 33 of file Pen.java.
References actor.Pen.mySize.
Referenced by properties.PenProperties.size().
boolean actor.Pen.isDown ()
Definition at line 41 of file Pen.java.
References actor.Pen.myDown.
Referenced by command.PenQueryCommand.execute(), and properties.PenProperties.isDown().
void actor.Pen.setColorIndex (int i)
Definition at line 53 of file Pen.java.
void actor.Pen.setDown (boolean b)
Definition at line 45 of file Pen.java.
void actor.Pen.setSize (double size)
Definition at line 37 of file Pen.java.
Member Data Documentation
final int actor.Pen.DEFAULT_COLOR_INDEX = 1 static private
Definition at line 9 of file Pen.java.
Referenced by actor.Pen.Pen().
final double actor.Pen.DEFAULT_SIZE = 1 static private
Definition at line 8 of file Pen.java.
Referenced by actor.Pen.Pen().
int actor.Pen.myColorIndex private
Definition at line 12 of file Pen.java.
Referenced by actor.Pen.getColorIndex().
boolean actor.Pen.myDown private
Definition at line 10 of file Pen.java.
Referenced by actor.Pen.isDown().
int actor.Pen.myID private
Definition at line 13 of file Pen.java.
Referenced by actor.Pen.getID().
double actor.Pen.mySize private
Definition at line 11 of file Pen.java.
Referenced by actor.Pen.getSize().
The documentation for this class was generated from the following file:
/tmp/duke-compsci308-fall2014/slogo_team09/repository/src/actor/Pen.java