slogo_team09: components.InfoPane Class Reference
components.InfoPane Class Reference
Public Member Functions
InfoPane (Controller c, String...s)
void update ()
Public Attributes
List< InfoTab > myTabs
Private Member Functions
ToolBar initiateToolBar (TabPane tabPane)
Detailed Description
Definition at line 30 of file InfoPane.java.
Constructor & Destructor Documentation
components.InfoPane.InfoPane (Controller c, String... s)
Definition at line 37 of file InfoPane.java.
References components.InfoPane.initiateToolBar(), and components.TabFactory.makeTab().
Member Function Documentation
ToolBar components.InfoPane.initiateToolBar (TabPane tabPane) private
Definition at line 63 of file InfoPane.java.
Referenced by components.InfoPane.InfoPane().
void components.InfoPane.update ()
Implements features.Feature.
Definition at line 60 of file InfoPane.java.
Member Data Documentation
List<InfoTab> components.InfoPane.myTabs
Initializes the display area for console history as well as error display
Definition at line 35 of file InfoPane.java.
Referenced by features.RunButtonFeature.updatePanes().
The documentation for this class was generated from the following file:
/tmp/duke-compsci308-fall2014/slogo_team09/repository/src/components/InfoPane.java