slogo_team09: features.DisplayTurtle Class Reference
features.DisplayTurtle Class Reference
Public Member Functions
DisplayTurtle (CenterPane pane)
void updatePosition (Position pos)
void updatePenType (int type)
void updateImage ()
void updateTurtleShow (boolean show)
void updatePenShow (boolean isPenDown)
void updateAnimate (boolean animateBool)
void updateSpeed (double speed)
void updateImageView (ImageView imageView)
Public Attributes
double turtleX
double turtleY
double turtleAngle
Pen myPen
boolean isTurtleShowing
double animationSpeed
Line myLine
ImageView myImage
Private Member Functions
void animateTurtlePosition ()
void animateTurtleAngle ()
void updateLine ()
Private Attributes
double turtleWidth
double turtleHeight
CenterPane myCenterPane
boolean penDown
double middleX
double middleY
double currentX
double currentY
int penType
boolean animate
double currentAngle
double time
Detailed Description
Definition at line 18 of file DisplayTurtle.java.
Constructor & Destructor Documentation
features.DisplayTurtle.DisplayTurtle (CenterPane pane)
Definition at line 41 of file DisplayTurtle.java.
References features.DisplayTurtle.updateImage().
Member Function Documentation
void features.DisplayTurtle.animateTurtleAngle () private
Calls the Rotate Transition which animates the rotation of turtle
Definition at line 111 of file DisplayTurtle.java.
References features.DisplayTurtle.myImage.
Referenced by features.DisplayTurtle.updatePosition().
void features.DisplayTurtle.animateTurtlePosition () private
Calls the Translate Transition when animation is turned on and turtle needs to be moved.
Definition at line 100 of file DisplayTurtle.java.
References features.DisplayTurtle.myImage, features.DisplayTurtle.turtleX, features.DisplayTurtle.turtleY, and features.DisplayTurtle.updateLine().
Referenced by features.DisplayTurtle.updatePosition().
void features.DisplayTurtle.updateAnimate (boolean animateBool)
updates whether or not the turtle's movements should be animated
Parameters
animateBool boolean that states whether or not animation should be turned on
Definition at line 177 of file DisplayTurtle.java.
void features.DisplayTurtle.updateImage ()
Updates the image position as well as angle (no animation)
Definition at line 132 of file DisplayTurtle.java.
References features.DisplayTurtle.turtleX, and features.DisplayTurtle.turtleY.
Referenced by features.DisplayTurtle.DisplayTurtle(), and features.DisplayTurtle.updatePosition().
void features.DisplayTurtle.updateImageView (ImageView imageView)
Definition at line 189 of file DisplayTurtle.java.
Referenced by components.TurtleManager.update().
void features.DisplayTurtle.updateLine () private
draws the line by calling appropriate method in pen class and displays it if needed
Definition at line 156 of file DisplayTurtle.java.
References features.Pen.drawLine().
Referenced by features.DisplayTurtle.animateTurtlePosition(), and features.DisplayTurtle.updatePosition().
void features.DisplayTurtle.updatePenShow (boolean isPenDown)
updates the pen to draw or not draw
Parameters
isPenDown boolean that states whether or not pen should be drawing
Definition at line 169 of file DisplayTurtle.java.
Referenced by components.TurtleManager.updatePenProperties().
void features.DisplayTurtle.updatePenType (int type)
Updates the type of pen to the right ID
Parameters
type integer that corresponds to a type of line to be created
Definition at line 125 of file DisplayTurtle.java.
void features.DisplayTurtle.updatePosition (Position pos)
Receives position and angle information and calls the appropriate methods to move turtle
Parameters
pos Contains new (x,y) coordinate and new angle information
Definition at line 72 of file DisplayTurtle.java.
References features.DisplayTurtle.animateTurtleAngle(), features.DisplayTurtle.animateTurtlePosition(), features.DisplayTurtle.animationSpeed, features.DisplayTurtle.currentX, features.DisplayTurtle.currentY, properties.Position.getAngle(), properties.Position.getX(), properties.Position.getY(), features.DisplayTurtle.updateImage(), and features.DisplayTurtle.updateLine().
Referenced by components.TurtleManager.update().
void features.DisplayTurtle.updateSpeed (double speed)
updates the speed so animations can be accurate
Parameters
speed speed passed from the slider
Definition at line 184 of file DisplayTurtle.java.
void features.DisplayTurtle.updateTurtleShow (boolean show)
updates the turtle image to show or hide
Parameters
show boolean that states whether or not turtle should be showing
Definition at line 145 of file DisplayTurtle.java.
Referenced by components.TurtleManager.update().
Member Data Documentation
boolean features.DisplayTurtle.animate private
Definition at line 34 of file DisplayTurtle.java.
double features.DisplayTurtle.animationSpeed
Definition at line 36 of file DisplayTurtle.java.
Referenced by features.DisplayTurtle.updatePosition().
double features.DisplayTurtle.currentAngle private
Definition at line 35 of file DisplayTurtle.java.
double features.DisplayTurtle.currentX private
Definition at line 31 of file DisplayTurtle.java.
Referenced by features.DisplayTurtle.updatePosition().
double features.DisplayTurtle.currentY private
Definition at line 32 of file DisplayTurtle.java.
Referenced by features.DisplayTurtle.updatePosition().
boolean features.DisplayTurtle.isTurtleShowing
Definition at line 27 of file DisplayTurtle.java.
double features.DisplayTurtle.middleX private
Definition at line 29 of file DisplayTurtle.java.
double features.DisplayTurtle.middleY private
Definition at line 30 of file DisplayTurtle.java.
CenterPane features.DisplayTurtle.myCenterPane private
Definition at line 26 of file DisplayTurtle.java.
ImageView features.DisplayTurtle.myImage
Definition at line 39 of file DisplayTurtle.java.
Referenced by features.DisplayTurtle.animateTurtleAngle(), and features.DisplayTurtle.animateTurtlePosition().
Line features.DisplayTurtle.myLine
Definition at line 38 of file DisplayTurtle.java.
Pen features.DisplayTurtle.myPen
Definition at line 25 of file DisplayTurtle.java.
Referenced by components.TurtleManager.updatePenProperties().
boolean features.DisplayTurtle.penDown private
Definition at line 28 of file DisplayTurtle.java.
int features.DisplayTurtle.penType private
Definition at line 33 of file DisplayTurtle.java.
double features.DisplayTurtle.time private
Definition at line 37 of file DisplayTurtle.java.
double features.DisplayTurtle.turtleAngle
Definition at line 22 of file DisplayTurtle.java.
Referenced by components.TurtlesTab.update().
double features.DisplayTurtle.turtleHeight private
Definition at line 24 of file DisplayTurtle.java.
double features.DisplayTurtle.turtleWidth private
Definition at line 23 of file DisplayTurtle.java.
double features.DisplayTurtle.turtleX
Definition at line 20 of file DisplayTurtle.java.
Referenced by features.DisplayTurtle.animateTurtlePosition(), components.TurtlesTab.update(), and features.DisplayTurtle.updateImage().
double features.DisplayTurtle.turtleY
Definition at line 21 of file DisplayTurtle.java.
Referenced by features.DisplayTurtle.animateTurtlePosition(), components.TurtlesTab.update(), and features.DisplayTurtle.updateImage().
The documentation for this class was generated from the following file:
/tmp/duke-compsci308-fall2014/slogo_team09/repository/src/features/DisplayTurtle.java