slogo_team09: mainApplication.GUI Class Reference
mainApplication.GUI Class Reference
Public Member Functions
GUI (Controller controller, Scene s)
void update (Observable obs, Object props)
void initiateKeyPress (Scene s)
Public Attributes
int myGUIid
Static Public Attributes
static List< DisplayTurtle > myObjects
Protected Attributes
BottomPane myBottomPane
Package Functions
void initiate ()
Private Member Functions
void loadPanes ()
Private Attributes
Turtle myTurtle
CenterPane myCenterPane
Parser myParser
TopPane myTopPane
InfoPane myLeftPane
InfoPane myRightPane
Map< Integer, Color > colorsMap
Controller myController
Scene myScene
Detailed Description
Definition at line 46 of file GUI.java.
Constructor & Destructor Documentation
mainApplication.GUI.GUI (Controller controller, Scene s)
Definition at line 69 of file GUI.java.
Member Function Documentation
void mainApplication.GUI.initiate () package
Definition at line 74 of file GUI.java.
References mainApplication.Controller.createWorkspace(), mainApplication.GUI.initiateKeyPress(), and mainApplication.GUI.loadPanes().
Referenced by mainApplication.GUIShell.createNewButton(), mainApplication.GUIShell.createOpenButton(), and mainApplication.GUIShell.GUIShell().
void mainApplication.GUI.initiateKeyPress (Scene s)
Definition at line 156 of file GUI.java.
References mainApplication.Controller.parseAndEvaluate().
Referenced by mainApplication.GUI.initiate().
void mainApplication.GUI.loadPanes () private
Definition at line 82 of file GUI.java.
References features.SettingsBar.addAnimationSlider(), features.SettingsBar.addComboBox(), components.TopPane.addItems(), features.SettingsBar.addPenSlider(), components.PaneFactory.makePane(), features.FeatureSetUp.myFeatureMap, features.RunButtonFeature.myImageMap, components.TopPane.mySettingsBar, components.CenterPane.myTurtleManager, components.BottomPane.updateButton(), and components.TurtleManager.updateImageMap().
Referenced by mainApplication.GUI.initiate().
void mainApplication.GUI.update (Observable obs, Object props)
Definition at line 134 of file GUI.java.
References components.CenterPane.clearScreen(), mainApplication.Controller.getColors(), components.CenterPane.initiateColorsMap(), components.BottomPane.myErrors, components.CenterPane.updateBackgroundColor(), components.CenterPane.updatePenProperties(), and components.CenterPane.updateTurtlePosition().
Member Data Documentation
Map<Integer, Color> mainApplication.GUI.colorsMap private
Definition at line 62 of file GUI.java.
BottomPane mainApplication.GUI.myBottomPane protected
Definition at line 55 of file GUI.java.
Referenced by mainApplication.GUIShell.createOpenButton().
CenterPane mainApplication.GUI.myCenterPane private
Definition at line 53 of file GUI.java.
Controller mainApplication.GUI.myController private
Definition at line 64 of file GUI.java.
int mainApplication.GUI.myGUIid
Definition at line 60 of file GUI.java.
Referenced by mainApplication.GUIShell.createNewButton().
InfoPane mainApplication.GUI.myLeftPane private
Definition at line 58 of file GUI.java.
List<DisplayTurtle> mainApplication.GUI.myObjects static
Definition at line 67 of file GUI.java.
Parser mainApplication.GUI.myParser private
Definition at line 54 of file GUI.java.
InfoPane mainApplication.GUI.myRightPane private
Definition at line 59 of file GUI.java.
Scene mainApplication.GUI.myScene private
Definition at line 65 of file GUI.java.
TopPane mainApplication.GUI.myTopPane private
Definition at line 56 of file GUI.java.
Turtle mainApplication.GUI.myTurtle private
Activates the necessary components for GUI
Definition at line 52 of file GUI.java.
The documentation for this class was generated from the following file:
/tmp/duke-compsci308-fall2014/slogo_team09/repository/src/mainApplication/GUI.java