slogo_team09: features.RunButtonFeature Class Reference
features.RunButtonFeature Class Reference
Public Member Functions
RunButtonFeature (Map< String, Pane > componentMap, Controller control)
void update ()
Public Attributes
Map< Integer, ImageView > myImageMap
Private Member Functions
void updatePanes ()
Map< Integer, ImageView > makeImageMap ()
Private Attributes
Controller myController
LeftPane myLeftPane
RightPane myRightPane
CenterPane myCenterPane
Button myButton
Detailed Description
Definition at line 29 of file RunButtonFeature.java.
Constructor & Destructor Documentation
features.RunButtonFeature.RunButtonFeature (Map< String, Pane > componentMap, Controller control)
Creates the run button that runs commands and also holds methods for interaction between command history and command area
Parameters
componentMap
control
Definition at line 43 of file RunButtonFeature.java.
References features.RunButtonFeature.makeImageMap(), components.BottomPane.myCommand, mainApplication.Controller.parseAndEvaluate(), features.RunButtonFeature.update(), and components.BottomPane.updateErrors().
Member Function Documentation
Map<Integer, ImageView> features.RunButtonFeature.makeImageMap () private
Definition at line 124 of file RunButtonFeature.java.
Referenced by features.RunButtonFeature.RunButtonFeature().
void features.RunButtonFeature.update ()
Implements features.Feature.
Definition at line 87 of file RunButtonFeature.java.
References features.RunButtonFeature.updatePanes().
Referenced by features.RunButtonFeature.RunButtonFeature().
void features.RunButtonFeature.updatePanes () private
Definition at line 93 of file RunButtonFeature.java.
References mainApplication.Controller.getColors(), mainApplication.Controller.getCommands(), mainApplication.Controller.getVariables(), components.InfoPane.myTabs, components.CenterPane.myTurtleManager, and components.TurtleManager.updateImageMap().
Referenced by features.RunButtonFeature.update().
Member Data Documentation
Button features.RunButtonFeature.myButton private
Definition at line 34 of file RunButtonFeature.java.
CenterPane features.RunButtonFeature.myCenterPane private
Definition at line 33 of file RunButtonFeature.java.
Controller features.RunButtonFeature.myController private
Definition at line 30 of file RunButtonFeature.java.
Map<Integer, ImageView> features.RunButtonFeature.myImageMap
Definition at line 35 of file RunButtonFeature.java.
Referenced by mainApplication.GUI.loadPanes().
LeftPane features.RunButtonFeature.myLeftPane private
Definition at line 31 of file RunButtonFeature.java.
RightPane features.RunButtonFeature.myRightPane private
Definition at line 32 of file RunButtonFeature.java.
The documentation for this class was generated from the following file:
/tmp/duke-compsci308-fall2014/slogo_team09/repository/src/features/RunButtonFeature.java