slogo_team09: parser.Parser Class Reference
parser.Parser Class Reference
Public Member Functions
Parser ()
List< Node > parse (String s) throws Exception
void changeLanguage (String language)
Private Member Functions
Node makeTree (String[] s) throws Exception
Node makeNode (String command) throws Exception
Private Attributes
List< Node > myTreeHeads
int myIndex
ResourceBundle myLanguage
ResourceBundle myCommands
Static Private Attributes
static final String RESOURCE_BUNDLE = "resources.languages/"
static final String COMMAND_BUNDLE = "resources.languages/Command"
static final String DEFAULT_LANGUAGE = "English"
static final String COMMENT_KEY = "Comment"
static final String NEW_LINE_REGEX = "[\\\t|\\\n|\\\r]"
static final String SPACE_REGEX = "\\s+"
Detailed Description
Parser converts string to graph of nodes with commands contained inside
Author
Chase Malik, Timesh Patel
Definition at line 18 of file Parser.java.
Constructor & Destructor Documentation
parser.Parser.Parser ()
Definition at line 31 of file Parser.java.
References parser.Parser.changeLanguage().
Member Function Documentation
void parser.Parser.changeLanguage (String language)
Change Language for parser
Parameters
language
Definition at line 64 of file Parser.java.
Referenced by parser.Parser.Parser(), and mainApplication.Controller.setLanguage().
Node parser.Parser.makeNode (String command) throws Exception private
Makes Node with given command
Parameters
command
Returns
Node with command
Exceptions
Exception
Definition at line 107 of file Parser.java.
References parser.CommandFactory.createCommand().
Referenced by parser.Parser.makeTree().
Node parser.Parser.makeTree (String[] s) throws Exception private
Makes Tree of nodes with commands
Parameters
s commands
Returns
Head of Tree
Exceptions
Exception
Definition at line 75 of file Parser.java.
References parser.Node.addChild(), parser.Node.getCommand(), command.Command.getNumInputs(), command.Command.isList(), parser.Parser.makeNode(), and command.Command.toString().
Referenced by parser.Parser.parse().
List<Node> parser.Parser.parse (String s) throws Exception
takes in a string and parses it by puts all commands into a graph of Nodes
Parameters
string
Returns
the string used if the commands were successful
Definition at line 44 of file Parser.java.
References parser.Parser.makeTree(), and parser.Parser.myTreeHeads.
Referenced by mainApplication.Controller.parseAndEvaluate(), parser.TestParser.TestBoolean(), parser.TestParser.TestDif(), parser.TestParser.TestFor(), parser.TestParser.TestForward(), parser.TestParser.TestIf(), parser.TestParser.TestIfElse(), parser.TestParser.TestMake(), parser.TestParser.TestMinus(), parser.TestModel.testParseException(), parser.TestModel.testPosition(), parser.TestParser.TestPow(), parser.TestParser.TestProd(), parser.TestParser.TestQuotient(), parser.TestParser.TestRandom(), parser.TestParser.TestRecursion(), parser.TestParser.TestRemainder(), parser.TestParser.TestRepeat(), parser.TestParser.TestSum(), parser.TestParser.TestSum2(), parser.TestParser.TestTo(), parser.TestParser.TestTrig(), and parser.TestModel.testWrite().
Member Data Documentation
final String parser.Parser.COMMAND_BUNDLE = "resources.languages/Command" static private
Definition at line 21 of file Parser.java.
final String parser.Parser.COMMENT_KEY = "Comment" static private
Definition at line 23 of file Parser.java.
final String parser.Parser.DEFAULT_LANGUAGE = "English" static private
Definition at line 22 of file Parser.java.
ResourceBundle parser.Parser.myCommands private
Definition at line 29 of file Parser.java.
int parser.Parser.myIndex private
Definition at line 27 of file Parser.java.
ResourceBundle parser.Parser.myLanguage private
Definition at line 28 of file Parser.java.
List<Node> parser.Parser.myTreeHeads private
Definition at line 26 of file Parser.java.
Referenced by parser.Parser.parse().
final String parser.Parser.NEW_LINE_REGEX = "[\\\t|\\\n|\\\r]" static private
Definition at line 24 of file Parser.java.
final String parser.Parser.RESOURCE_BUNDLE = "resources.languages/" static private
Definition at line 20 of file Parser.java.
final String parser.Parser.SPACE_REGEX = "\\s+" static private
Definition at line 25 of file Parser.java.
The documentation for this class was generated from the following file:
/tmp/duke-compsci308-fall2014/slogo_team09/repository/src/parser/Parser.java