slogo_team09: actor.Turtle Class Reference
actor.Turtle Class Reference
Public Member Functions
Turtle (Position pos, int id)
Turtle (int id)
double getX ()
double getY ()
Point2D getPoint ()
double getAngle ()
int getID ()
Position getPosition ()
Pen getPen ()
void updatePosition (double newX, double newY, double newAngle)
void setShowing (boolean showing)
void setChangedandNotify (Object obj)
boolean isActive ()
void setActive (boolean active)
boolean isShowing ()
void changedPen ()
void changeShape (int index)
int getShape ()
Private Attributes
Position myPosition
int myID
Pen myPen
boolean myActive
boolean myShowing
int myShape
Static Private Attributes
static final Position DEFAULT_POSITION = new Position(0, 0, Math.PI / 2)
static final int DEFAULT_SHAPE = 0
Detailed Description
Definition at line 13 of file Turtle.java.
Constructor & Destructor Documentation
actor.Turtle.Turtle (Position pos, int id)
Turtle class represents the turtle in the backend contains a default shape index, a position, a pen, an id and active and showing booleans the turtle has get methods on some its properties for convenience
Parameters
pos
id
Definition at line 32 of file Turtle.java.
References actor.Turtle.DEFAULT_SHAPE.
actor.Turtle.Turtle (int id)
Definition at line 41 of file Turtle.java.
References actor.Turtle.DEFAULT_POSITION.
Member Function Documentation
void actor.Turtle.changedPen ()
Definition at line 100 of file Turtle.java.
References actor.Turtle.setChangedandNotify().
void actor.Turtle.changeShape (int index)
Definition at line 104 of file Turtle.java.
References actor.Turtle.setChangedandNotify().
double actor.Turtle.getAngle ()
Definition at line 57 of file Turtle.java.
References properties.Position.getAngle().
Referenced by command.HeadingCommand.execute().
int actor.Turtle.getID ()
Definition at line 61 of file Turtle.java.
References actor.Turtle.myID.
Referenced by properties.TurtleProperties.TurtleProperties().
Pen actor.Turtle.getPen ()
Definition at line 69 of file Turtle.java.
References actor.Turtle.myPen.
Referenced by command.PenQueryCommand.execute(), command.GetPenColorCommand.execute(), and properties.TurtleProperties.TurtleProperties().
Point2D actor.Turtle.getPoint ()
Definition at line 53 of file Turtle.java.
References properties.Position.getPoint().
Position actor.Turtle.getPosition ()
Definition at line 65 of file Turtle.java.
References actor.Turtle.myPosition.
Referenced by properties.TurtleProperties.TurtleProperties().
int actor.Turtle.getShape ()
Definition at line 109 of file Turtle.java.
References actor.Turtle.myShape.
Referenced by command.GetShapeCommand.execute(), and properties.TurtleProperties.TurtleProperties().
double actor.Turtle.getX ()
Definition at line 45 of file Turtle.java.
References properties.Position.getX().
Referenced by command.XCoordinateCommand.execute(), and parser.TestParser.TestTo().
double actor.Turtle.getY ()
Definition at line 49 of file Turtle.java.
References properties.Position.getY().
Referenced by command.YCoordinateCommand.execute().
boolean actor.Turtle.isActive ()
Definition at line 88 of file Turtle.java.
References actor.Turtle.myActive.
boolean actor.Turtle.isShowing ()
Definition at line 96 of file Turtle.java.
References actor.Turtle.myShowing.
Referenced by command.ShowingQueryCommand.execute(), and properties.TurtleProperties.TurtleProperties().
void actor.Turtle.setActive (boolean active)
Definition at line 92 of file Turtle.java.
void actor.Turtle.setChangedandNotify (Object obj)
Definition at line 83 of file Turtle.java.
Referenced by actor.Turtle.changedPen(), actor.Turtle.changeShape(), workspace.Workspace.createTurtle(), actor.Turtle.setShowing(), and actor.Turtle.updatePosition().
void actor.Turtle.setShowing (boolean showing)
Definition at line 78 of file Turtle.java.
References actor.Turtle.setChangedandNotify().
void actor.Turtle.updatePosition (double newX, double newY, double newAngle)
Definition at line 73 of file Turtle.java.
References actor.Turtle.setChangedandNotify().
Member Data Documentation
final Position actor.Turtle.DEFAULT_POSITION = new Position(0, 0, Math.PI / 2) static private
Definition at line 14 of file Turtle.java.
Referenced by actor.Turtle.Turtle().
final int actor.Turtle.DEFAULT_SHAPE = 0 static private
Definition at line 15 of file Turtle.java.
Referenced by actor.Turtle.Turtle().
boolean actor.Turtle.myActive private
Definition at line 19 of file Turtle.java.
Referenced by actor.Turtle.isActive().
int actor.Turtle.myID private
Definition at line 17 of file Turtle.java.
Referenced by actor.Turtle.getID().
Pen actor.Turtle.myPen private
Definition at line 18 of file Turtle.java.
Referenced by actor.Turtle.getPen().
Position actor.Turtle.myPosition private
Definition at line 16 of file Turtle.java.
Referenced by actor.Turtle.getPosition().
int actor.Turtle.myShape private
Definition at line 21 of file Turtle.java.
Referenced by actor.Turtle.getShape().
boolean actor.Turtle.myShowing private
Definition at line 20 of file Turtle.java.
Referenced by actor.Turtle.isShowing().
The documentation for this class was generated from the following file:
/tmp/duke-compsci308-fall2014/slogo_team09/repository/src/actor/Turtle.java