slogo_team09: command.TellCommand Class Reference
command.TellCommand Class Reference
Public Member Functions
TellCommand (String s)
double execute (List< Node > inputs, Workspace workspace) throws Exception
Public Member Functions inherited from command.BaseMultiTurtleCommand
BaseMultiTurtleCommand (String s, int numInputs, int numLists)
Public Member Functions inherited from command.BasicListCommand
BasicListCommand (String s, int numInputs, int numLists)
boolean checkListExit (Node node)
void checkListException (List< Node > inputs) throws Exception
int getBracketIndex (List< Node > inputs)
Public Member Functions inherited from command.Command
Command (String s)
int getNumInputs (Node node)
String toString ()
boolean isList ()
abstract double execute (List< Node > inputs, Workspace workspace) throws Exception
Additional Inherited Members
Protected Member Functions inherited from command.BaseMultiTurtleCommand
List< Integer > getIds (List< Turtle > turtles)
List< Integer > getIdsList (List< Node > inputs, Workspace workspace) throws Exception
void tell (List< Integer > ids, Workspace workspace)
Protected Member Functions inherited from command.Command
Command (String s, int numInputs)
boolean checkListExit (Node node)
Protected Attributes inherited from command.Command
int myNumInputs
int myListFlag
String myString
Detailed Description
Definition at line 8 of file TellCommand.java.
Constructor & Destructor Documentation
command.TellCommand.TellCommand (String s)
Definition at line 10 of file TellCommand.java.
Member Function Documentation
double command.TellCommand.execute (List< Node > inputs, Workspace workspace) throws Exception
Definition at line 16 of file TellCommand.java.
References command.BasicListCommand.checkListException(), command.BaseMultiTurtleCommand.getIdsList(), and command.BaseMultiTurtleCommand.tell().
The documentation for this class was generated from the following file:
/tmp/duke-compsci308-fall2014/slogo_team09/repository/src/command/TellCommand.java