slogo_team09: components.BottomPane Class Reference
components.BottomPane Class Reference
Public Member Functions
BottomPane ()
void updateButton (Button run)
void updateErrors (Exception e)
Public Attributes
final TextArea myCommand
final Label myErrors
Detailed Description
Definition at line 11 of file BottomPane.java.
Constructor & Destructor Documentation
components.BottomPane.BottomPane ()
Definition at line 15 of file BottomPane.java.
Member Function Documentation
void components.BottomPane.updateButton (Button run)
adds a button to the bottom pane
Parameters
run button to be added to bottom pane
Definition at line 40 of file BottomPane.java.
Referenced by mainApplication.GUI.loadPanes().
void components.BottomPane.updateErrors (Exception e)
displays errors in the right text areas
Parameters
e errors that are to be displayed
Definition at line 48 of file BottomPane.java.
Referenced by mainApplication.GUIShell.createOpenButton(), and features.RunButtonFeature.RunButtonFeature().
Member Data Documentation
final TextArea components.BottomPane.myCommand
Definition at line 12 of file BottomPane.java.
Referenced by features.RunButtonFeature.RunButtonFeature().
final Label components.BottomPane.myErrors
Definition at line 13 of file BottomPane.java.
Referenced by mainApplication.GUI.update().
The documentation for this class was generated from the following file:
/tmp/duke-compsci308-fall2014/slogo_team09/repository/src/components/BottomPane.java